#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long;
use Carp;

my ($stdin, $regexp, $upper, $lower, $equal);
GetOptions(
  "stdin"    => \$stdin,
  "regexp=s" => \$regexp,
  "upper=s"  => \$upper,
  "lower=s"  => \$lower,
  "equal=s"  => \$equal,
);

my $data = qq{};

# とりあえずは標準入力モードのみ
$stdin = 1;
if ($stdin) {
  $data = <STDIN>;
}

my $version;
if (defined $regexp) {
  my $regexp_compiled = qr/$regexp/;
  if ($data =~ /$regexp_compiled/) {
    $version = $1;
  } else {
     croak qq{not match /$regexp_compiled/ in string "$data"};
  }
} else {
  if ($data =~ /([\d\.]+)/) {
    $version = $1;
  } else {
    chomp( $version = $data );
  }
}

if (! $version) {
  croak qq{version number can't be gotton};
}

my @fails;
if (defined $upper) {
  # upperより小さかったらダメ
  if (_trim( $upper ) > _trim( $version ) ) {
    push @fails, qq{current: $version < $upper};
  }
}
if (defined $lower) {
  # lowerより大きかったらダメ
  if (_trim( $lower ) < _trim( $version ) ) {
    push @fails, qq{current: $version > $lower};
  }
}
if (defined $equal) {
  # equalと同じでなければダメ
  if (_trim( $equal ) != _trim( $version ) ) {
    push @fails, qq{current: $version != $equal};
  }
}

if (@fails == 0) {
  print "version is valid( $version )\n";
  exit 0;
} else {
  print "version is INVALID( $version )\n";
  exit 1;
}

sub _trim {
  my $version = shift;
  if (defined $version) {
    $version =~ s{[_\-\.]}{}g;
  }
  $version;
}

