#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename;
use File::Spec;
use Carp;

our $keyname = ".tmp-key";
my $name     = basename $0;
my $mypath   = dirname ( File::Spec->rel2abs( $0 ) );
my @paths    = split /:/, $ENV{PATH};

my $command_full_path;
for my $path ( @paths ) {
  $path =~ /^$mypath/ and next;
  if (-x "$path/$name") {
    $command_full_path = "$path/$name";
  }
}

if (! $command_full_path) {
  croak "$name command not found";
}

my $key_path = "$mypath/../$keyname";
my $command  = $command_full_path;
   $command .= " -i $key_path" if -f $key_path;
   $command .= " " . ( join " ", @ARGV );

{ 
  use FindBin;
  use lib qq{$FindBin::Bin/../lib};
  use Roccaku::Utils;
  logging "$mypath/$keyname";
  logging "| $name ||||||||||||| $command";
  exec $command;
}
