#!/usr/bin/env perl
use strict;
use warnings;
use File::Basename;
use File::Spec;
use Carp;

our $keyname = ".tmp-key";
my $name     = basename $0;
my $mypath   = dirname ( File::Spec->rel2abs( $0 ) );
my @paths    = split /:/, $ENV{PATH};

my $command_full_path;
for my $path ( @paths ) {
  $path =~ /^$mypath/ and next;
  if (-x "$path/ssh") {
    $command_full_path = "$path/ssh";
  }
}

if (! $command_full_path) {
  croak "$name command not found";
}

my $command  = $command_full_path;
   $command .= " -i $mypath/$keyname" if -f "$mypath/$keyname";
   $command .= " " . ( join " ", @ARGV );
warn "||||||||||||| $command";
exec $command;
